target("easy_test")
add_deps("nes")
set_kind("binary")
add_files("easy_test.cc")
add_packages("gtest", "raylib")

target("snake_test")
add_deps("nes")
set_kind("binary")
add_files("snake_test.cc")
add_packages("raylib")
